# site title
title: The Zeitgeist Movement

# site subtitle
subtitle: Shire chapter

#chapter_name - used in the About {{chapter_name}} menu option
chapter_name: Shire

# site description
description: >- # this means to ignore newlines until "baseurl:"
  Template for the Zeigeist Movement Chapter site.

# site author
author: Zeitgeist movement

# site contact email
email: your-email@example.com

# site avatar
avatar: /assets/images/avatar.jpg

# footer text
footer_text: The Zeitgeist Movement

#google font
google_fonts: "Fjalla+One|Cantarell"

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://template.tzm.community" # the base hostname & protocol for your site

# View an message that will be show on every page
show_alert: true

# Alert text that will be show on every page
alert_text: This is currently an example template page. TZMCommunity template engine is a way to create sites that are well performing and easy to setup. Check out docs here <a href="https://tzmcommunity.github.io/docs/">https://tzmcommunity.github.io/docs/</a>

# Assets
assets:
    sources:
        - _assets/images
        - _assets/stylesheets
        - _assets/images/slides

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
youtube_url:

#Global TZM URLs:
tzm_global_facebook_url: "https://www.facebook.com/tzmglobal"
tzm_global_instagram_url: "https://www.instagram.com/tzmglobal/"
tzm_global_twitter_url: "https://twitter.com/tzmglobal"
tzm_global_youtube_url: "https://www.youtube.com/user/TZMOfficialChannel"

# Google Analytics Tracking ID goes here:
google_analytics:

plugins: [ jekyll-assets, jekyll-seo-tag, jekyll-toc, jekyll-sitemap, jekyll-feed ]

collections:
    events:
        output: true

# where to cut a page when showing only excerpt
excerpt_separator: "<!--more-->"

# if true, index content shown in home page
show_content_on_homepage: true

# if true, post excerpts will be shown in home page
show_posts_on_homepage: true

# if true, posts will be shown in two columns
posts_two_col: false

# if true, posts will be shown in three columns
posts_three_col: true

# maximum number of posts show on home page
posts_max_home: 3

# if true, links to events will be shown in home page
show_events_on_homepage: true

# if true, site will be divided with a sidepanel
#sidepanel: true

# if true, news widger will be shown in the sidepanel
#sidepanel_news: true

# news widget url
news_widget_url: "https://news.tzm.community/widget.html"

# are menu titles are clickable links or do they open a menu
# false works better for mobile clients.
menu_clickable: false

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
