title: Your awesome title
subtitle: Your awesome subtitle
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Your Incredible Name
email: your-email@example.com
avatar: /assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

assets:
    sources:
        - _assets/images          
        - _assets/stylesheets          
        - _assets/images/slides

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

plugins: [ jekyll-assets ]
collections: [sections]
