# site title
title: The Zeitgeist Movement

# site subtitle
subtitle: Shire chapter

# site description
description: >- # this means to ignore newlines until "baseurl:"
  Template for the Zeigeist Movement Chapter site.

# site author
author: Zeitgeist movement

# site contact email
email: your-email@example.com

# site avatar
avatar: /assets/images/avatar.jpg

# footer text
footer_text: The Zeitgeist Movement

#google font
google_fonts: "Fjalla+One|Roboto"

# You'll want to customize url and baseurl for your own site:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

assets:
    sources:
        - _assets/images          
        - _assets/stylesheets          
        - _assets/images/slides

# Social settings
facebook_url:
github_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Google Analytics Tracking ID goes here:
google_analytics:

plugins: [ jekyll-assets, jekyll-seo-tag, jekyll-toc ]

collections: 
    events:
        output: true

# where to cut a page when showing only excerpt
excerpt_separator: "<!--more-->"

# if true, post excerpts will be shown in home page
show_posts_on_homepage: true

# if true, links to events will be shown in home page
show_events_on_homepage: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
      
